### ISSUE TITLE
Fork a fork of this repository

### ISSUE THREAD

**Issue by penyuan** [OPEN-NEXT/wp2.2_reference#5]
@rafaellaantoniou already made of fork of this repository, I will make one more of it (i.e. a fork of @rafaellaantoniou's fork).

**Comment by jbon** [comment]
as discussed with @penyuan I created a fork of Rafaella#s fork, made a commit and deleted the fork.
Note that I first forked the original directory by error and deleted it so I can make a fork of Rafaella's fork

**Comment by penyuan** [comment]
Thanks @jbon!

Unfortunately it looks like after you deleted your forks, no record of it remains. I tried to create a fork (I tried forking the original *and* @rafaellaantoniou's fork), but GitHub claims I've already forked it and wouldn't allow me to make another fork.

@jbon: When you get a chance, can you try forking @rafaellaantoniou's fork again, add a commit (or two), but **don't** delete for now? I'd just like to see if that will at least make it appear in GitHub's network visulisation. Thanks!

**Comment by jbon** [comment]
"_@jbon: When you get a chance, can you try forking @rafaellaantoniou's fork again, add a commit (or two), but don't delete for now?_"

Done

**Comment by penyuan** [comment]
Thank you @jbon, I can see it in GitHub's graph now.

I don't know why a removed fork would not appear in the count of forks as I have seen in other projects. However, I think I will close this issue for now because I think this repository is basically good enough to be used as a test case for the script.

Everyone: Please do chime in in case you have other thoughts/comments/concerns about whether this repository is good enough for the stated purpose.
